import { useEffect, useMemo, useState } from 'react';
import { Mail, Search, Users } from 'lucide-react';
import API from '../../services/api';

export default function FormateurApprenants() {
  const [students, setStudents] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { API.get('/formateur/apprenants').then((response) => setStudents(response.data)).catch(console.error).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => students.filter((student) => `${student.nom} ${student.prenom} ${student.email} ${student.formation_titre}`.toLowerCase().includes(search.toLowerCase())), [students, search]);
  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 border-b border-black/10 pb-6 sm:flex-row sm:items-end dark:border-white/10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-orange-600 dark:text-orange-400">Suivi pédagogique</p><h1 className="mt-2 text-3xl font-black">Mes apprenants</h1><p className="mt-2 text-sm text-black/55 dark:text-white/55">Les apprenants inscrits à vos formations.</p></div><div className="flex items-center gap-2 text-sm font-bold"><Users size={19} className="text-orange-500" /> {students.length} apprenant(s)</div></div><div className="relative"><Search size={17} className="absolute left-3 top-3.5 text-black/40" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher un apprenant ou une formation" className="w-full rounded-xl border border-black/15 bg-transparent py-3 pl-10 pr-4 text-sm outline-none focus:border-orange-500 dark:border-white/20" /></div>{loading ? <p className="py-10 text-center text-sm text-black/50">Chargement...</p> : filtered.length === 0 ? <div className="rounded-2xl border border-dashed border-black/15 p-12 text-center text-sm text-black/50 dark:border-white/15">Aucun apprenant trouvé.</div> : <div className="grid gap-4 md:grid-cols-2">{filtered.map((student) => <article key={`${student.id_apprenant}-${student.id_formation}`} className="rounded-2xl border border-black/10 bg-white p-5 dark:border-white/10 dark:bg-zinc-950"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-orange-500 text-sm font-black text-black">{student.prenom?.[0]}{student.nom?.[0]}</div><div className="min-w-0 flex-1"><h2 className="font-black">{student.prenom} {student.nom}</h2><p className="truncate text-sm text-black/55 dark:text-white/55">{student.email}</p></div><a href={`mailto:${student.email}`} title="Envoyer un email" className="rounded-lg p-2 text-orange-600 hover:bg-orange-500/10"><Mail size={17} /></a></div><div className="mt-5 border-t border-black/10 pt-4 dark:border-white/10"><p className="text-xs font-bold uppercase tracking-wider text-orange-600 dark:text-orange-400">Formation</p><p className="mt-1 text-sm font-semibold">{student.formation_titre}</p></div></article>)}</div>}</div>;
}
