import { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, CalendarDays, ClipboardCheck, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import API from '../../services/api';

export default function FormateurDashboard() {
	const [formations, setFormations] = useState([]);
	const [loading, setLoading] = useState(true);
	useEffect(() => {
		API.get('/formateur/formations').then((response) => setFormations(response.data)).catch(console.error).finally(() => setLoading(false));
	}, []);
	return <div className="space-y-8">
		<div><p className="text-xs font-bold uppercase tracking-[0.2em] text-orange-600 dark:text-orange-400">Espace formateur</p><h1 className="mt-2 text-3xl font-black tracking-tight">Votre espace de pilotage</h1><p className="mt-2 max-w-2xl text-sm text-black/55 dark:text-white/55">Retrouvez vos formations, vos apprenants et vos évaluations au même endroit.</p></div>
		<div className="grid gap-4 sm:grid-cols-3"><Link to="/Formateur/Planning" className="rounded-2xl border border-black/10 bg-orange-500 p-5 text-black shadow-lg shadow-orange-500/15 transition hover:-translate-y-1"><CalendarDays /><strong className="mt-6 block text-lg">Mon planning</strong><span className="mt-1 block text-sm text-black/65">Consulter vos séances</span></Link><Link to="/Formateur/Apprenants" className="rounded-2xl border border-black/10 bg-white p-5 transition hover:-translate-y-1 dark:border-white/10 dark:bg-zinc-950"><Users className="text-orange-500" /><strong className="mt-6 block text-lg">Mes apprenants</strong><span className="mt-1 block text-sm text-black/55 dark:text-white/55">Suivre vos groupes</span></Link><Link to="/Formateur/Evaluations" className="rounded-2xl border border-black/10 bg-white p-5 transition hover:-translate-y-1 dark:border-white/10 dark:bg-zinc-950"><ClipboardCheck className="text-orange-500" /><strong className="mt-6 block text-lg">Évaluations</strong><span className="mt-1 block text-sm text-black/55 dark:text-white/55">Créer et publier</span></Link></div>
		<section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-xl font-black">Mes formations</h2><p className="mt-1 text-sm text-black/50 dark:text-white/50">Formations qui vous sont assignées</p></div><BookOpen className="text-orange-500" /></div>{loading ? <p className="py-8 text-center text-sm text-black/50">Chargement...</p> : formations.length === 0 ? <div className="rounded-2xl border border-dashed border-black/15 p-10 text-center text-sm text-black/50 dark:border-white/15 dark:text-white/50">Aucune formation assignée.</div> : <div className="grid gap-4 md:grid-cols-2">{formations.map((formation) => <div key={formation.id_formation} className="rounded-2xl border border-black/10 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-zinc-950"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-black">{formation.titre}</h3><p className="mt-1 line-clamp-2 text-sm text-black/55 dark:text-white/55">{formation.description}</p></div><span className="rounded-full bg-orange-500/10 px-2.5 py-1 text-xs font-bold text-orange-700 dark:text-orange-400">{formation.statut}</span></div><div className="mt-5 flex items-center justify-between border-t border-black/10 pt-4 text-sm dark:border-white/10"><span>{formation.apprenants_count || 0} apprenant(s)</span><Link to={`/Formateur/Evaluations?formation=${formation.id_formation}`} className="flex items-center gap-1 font-bold text-orange-600 dark:text-orange-400">Gérer <ArrowRight size={15} /></Link></div></div>)}</div>}</section>
	</div>;
}
