import { useEffect, useState } from 'react';
import { Send } from 'lucide-react';
import API from '../../services/api';

export default function FormateurForum() {
	const [forums, setForums] = useState([]); const [selected, setSelected] = useState(null); const [messages, setMessages] = useState([]); const [content, setContent] = useState('');
	useEffect(() => { API.get('/formateur/forums').then((response) => { setForums(response.data); if (response.data[0]) setSelected(response.data[0]); }).catch(console.error); }, []);
	useEffect(() => { if (selected) API.get(`/formateur/forums/${selected.id_forum}/messages`).then((response) => setMessages(response.data)).catch(console.error); }, [selected]);
	const send = async (event) => { event.preventDefault(); if (!content.trim() || !selected) return; await API.post(`/formateur/forums/${selected.id_forum}/messages`, { contenu: content }); setContent(''); const response = await API.get(`/formateur/forums/${selected.id_forum}/messages`); setMessages(response.data); };
	return <div className="space-y-7"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-orange-600 dark:text-orange-400">Communication</p><h1 className="mt-2 text-3xl font-black">Messagerie</h1><p className="mt-2 text-sm text-black/55 dark:text-white/55">Échangez avec les apprenants de vos formations.</p></div><div className="grid min-h-[520px] gap-4 lg:grid-cols-[280px_1fr]"><aside className="rounded-2xl border border-black/10 bg-white p-3 dark:border-white/10 dark:bg-zinc-950"><h2 className="px-3 py-2 text-sm font-black">Forums</h2>{forums.map((forum) => <button key={forum.id_forum} onClick={() => setSelected(forum)} className={`w-full rounded-xl p-3 text-left ${selected?.id_forum === forum.id_forum ? 'bg-orange-500 text-black' : 'hover:bg-black/5 dark:hover:bg-white/10'}`}><strong className="block text-sm">{forum.nom}</strong><span className="text-xs opacity-60">{forum.formation_titre}</span></button>)}{!forums.length && <p className="p-3 text-sm text-black/50">Aucun forum associé.</p>}</aside><section className="flex flex-col rounded-2xl border border-black/10 bg-white dark:border-white/10 dark:bg-zinc-950"><div className="border-b border-black/10 p-5 dark:border-white/10"><h2 className="font-black">{selected?.nom || 'Sélectionnez un forum'}</h2><p className="mt-1 text-xs text-black/50 dark:text-white/50">{selected?.formation_titre}</p></div><div className="flex-1 space-y-3 overflow-y-auto p-5">{messages.map((message) => <article key={message.id_message} className="rounded-xl bg-black/[0.03] p-3 dark:bg-white/[0.05]"><p className="text-xs font-bold text-orange-600">{message.prenom} {message.nom_expediteur}</p><p className="mt-1 text-sm">{message.contenu}</p></article>)}{selected && !messages.length && <p className="text-sm text-black/50">Aucun message pour le moment.</p>}</div><form onSubmit={send} className="flex gap-2 border-t border-black/10 p-4 dark:border-white/10"><input className="flex-1 rounded-xl border border-black/15 bg-transparent px-3 py-2.5 text-sm outline-none focus:border-orange-500 dark:border-white/20" placeholder="Écrire un message..." value={content} onChange={(event) => setContent(event.target.value)} /><button className="rounded-xl bg-orange-500 p-3 text-black" aria-label="Envoyer"><Send size={17} /></button></form></section></div></div>;
}
