import { useEffect, useState } from 'react';
import { CalendarDays, Clock, MapPin } from 'lucide-react';
import API from '../../services/api';

export default function FormateurPlanning() {
  const [seances, setSeances] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { API.get('/formateur/planning').then((response) => setSeances(response.data)).catch(console.error).finally(() => setLoading(false)); }, []);
  return <div className="space-y-7"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-orange-600 dark:text-orange-400">Organisation</p><h1 className="mt-2 text-3xl font-black">Mon planning</h1><p className="mt-2 text-sm text-black/55 dark:text-white/55">Vos séances dans les formations qui vous sont assignées.</p></div>{loading ? <p className="py-10 text-center text-sm text-black/50">Chargement...</p> : seances.length === 0 ? <div className="rounded-2xl border border-dashed border-black/15 p-12 text-center text-sm text-black/50 dark:border-white/15">Aucune séance programmée.</div> : <div className="space-y-3">{seances.map((seance) => <article key={seance.id_seance} className="flex flex-col gap-4 rounded-2xl border border-black/10 bg-white p-5 shadow-sm sm:flex-row sm:items-center dark:border-white/10 dark:bg-zinc-950"><div className="flex h-14 w-14 shrink-0 flex-col items-center justify-center rounded-xl bg-orange-500 text-black"><CalendarDays size={18} /><strong className="text-xs">{new Date(`${seance.date_seance}T00:00:00`).toLocaleDateString('fr-FR', { day: '2-digit', month: 'short' })}</strong></div><div className="flex-1"><p className="text-xs font-bold uppercase tracking-wider text-orange-600 dark:text-orange-400">{seance.formation_titre}</p><h2 className="mt-1 text-lg font-black">{seance.titre || 'Séance sans titre'}</h2><p className="mt-1 text-sm text-black/55 dark:text-white/55">{seance.description || 'Aucune description.'}</p></div><div className="flex flex-wrap gap-3 text-xs font-semibold text-black/60 dark:text-white/60"><span className="flex items-center gap-1"><Clock size={15} /> {seance.heure_debut} - {seance.heure_fin}</span>{seance.salle && <span className="flex items-center gap-1"><MapPin size={15} /> {seance.salle}</span>}</div></article>)}</div>}</div>;
}
